require("core.settings")
require("core.keymaps")

vim.cmd("set t_Co=256")
vim.cmd("colorscheme elflord")
vim.cmd("set background=dark")
-- require("configs.themes.nightfox").config()
-- require("configs.themes.kanagawa").config()
-- require("configs.themes.tokyonight").config()

require("configs.lualine").config()
require("core.plugins")
require("configs.nvim-tree").config()
require("configs.treesitter")
require("configs.lsp.lsp")
require("configs.lsp.dictionary")
require("configs.lsp.cmp")
require("configs.comment")
require("configs.telescope")
require("configs.markdown")
require("configs.dashboard").config()
require("configs.bufferline").config()
require("configs.blankline").config()
require("configs.leetcode").config()
require("configs.markdown")
